# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/ec4-v2-vue/vue+vite/" # Location of package manifests
    target-branch: "vue-rework-attempt"
    schedule:
      interval: "weekly"
